name: Node-Red

on:
  workflow_dispatch:
    inputs:
      node-red-version:
        description: 'Node-Red version'
        required: true
        default: '2.0.5'

jobs:
  build_multi_arch_images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push node-red
        id: docker_build
        uses: docker/build-push-action@v5.3.0
        with:
          context: node-red
          push: true
          tags: |
            cpswan/node-red:latest
            cpswan/node-red:${{ github.event.inputs.node-red-version }}
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7    